apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/gor-g/devops-basic-ks8-cluster:flask-app-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: pg-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db
              name: pg-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: pg-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-password
        livenessProbe:
          httpGet:
            path: "/"
            port: 5000
      initContainers:
      - name: wait-for-pg
        image: busybox:1.36.1
        command:
          - "sh"
          - "-c"
          - "until nc pg-service 5432 ; do sleep 5 ; done"
