name: Docker Image CI

on:
  push:
    branches: [ "nginx-app" ]
  pull_request:
    branches: [ "nginx-app" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/devops-basic-ks8-cluster:nginx-app-latest

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/devops-basic-ks8-cluster:nginx-app-latest
